require('dotenv').config()
const gamesRouter = require('./src/api/routes/gamesRoute')
const { connectDB } = require('./src/config/db')
const express = require('express')
const app = express()
connectDB()
app.use('/api/v1/games', gamesRouter)
app.use('*', (req, res, next) => res.status(404).json('route not foud'))
app.listen(4000, () => console.log('http://localhost:4000'))
